<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');

$this->headLink()->appendStylesheet($this->assetUrl('css/site/page.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/faceted-browse.js', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/site/page.js', 'FacetedBrowse'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('vendor/tablesaw/tablesaw.jquery.js', 'FacetedBrowse'));
$this->facetedBrowse()->prepareFacets();

$this->htmlElement('body')->appendAttribute('class', 'faceted-browse-page resource browse');
$this->headTitle($page->title());

$categories = $page->categories();
$categoryId = null;
if (1 === count($categories)) {
    $category = current($categories);
    $categoryId = $category->id();
}
?>

<section class="subpage-hero">
    <div class="container">
        <h1><?php echo $escape($page->title()); ?></h1>
    </div>
</section>

<section class="section">
    <div class="container">
        <div id="container"
            data-url-categories="<?php echo $escape($this->url(null, ['action' => 'categories'], true)); ?>"
            data-url-facets="<?php echo $escape($this->url(null, ['action' => 'facets'], true)); ?>"
            data-url-browse="<?php echo $escape($this->url(null, ['action' => 'browse'], true)); ?>"
            data-category-id="<?php echo $escape($categoryId); ?>">
            <button id="section-sidebar-modal-toggle" type="button"><?php echo $translate('Filters'); ?></button>
            <div id="section-sidebar" class="mobile modal-panel" aria-describedby="facet-modal-description" aria-label="<?php echo $translate('Filters'); ?>"></div>
            <div id="section-content"></div>
        </div>
    </div>
</section>

<script>
const container = $('#container');

container.on('click', '.select-list-expand', function(e) {
    e.preventDefault();
    const thisButton = $(this);
    const selectList = thisButton.closest('.facet').find('.select-list');
    selectList.addClass('expanded');
    FacetedBrowse.updateSelectList(selectList);
});

container.on('click', '.select-list-collapse', function(e) {
    e.preventDefault();
    const thisButton = $(this);
    const selectList = thisButton.closest('.facet').find('.select-list');
    selectList.removeClass('expanded');
    FacetedBrowse.updateSelectList(selectList);
});
</script>
